### PR TITLE
notes@schorschii: update/fix translations

### PR DESCRIPTION
**Pull request by schorschii**
- removed the 'fuzzy' flag which prevents translations from being displayed
- fixed wrong translations introduced with #1293

### CODE REVIEW

**Comment by rcalixte** [comment]
> * removed the 'fuzzy' flag which prevents translations from being displayed

These strings are inserted to represent that the translations should be double-checked. They are not prevented from being displayed. This notation allows tools with proper support to identify these fields for translators as well.

Going forward, can you make use of the repository scripts for translations or use Poedit and avoid editing them manually? Even Vim has plugins for translation file support if you would rather go that route.

**Review by rcalixte — APPROVED** [review]

**Comment by schorschii** [comment]
> These strings are inserted to represent that the translations should be double-checked. They are not prevented from being displayed.

My experience was different. I wondered why [these](https://github.com/linuxmint/cinnamon-spices-desklets/pull/1296/files#diff-0d94ba9734759268e959f4f49517d0bee86a53ab37d1d9254274d316e6c08166L68) German translations were not displayed. As soon as I removed the fuzzy flag and executed `cinnamon-spices-makepot notes@schorschii`, they were displayed correctly (yes, I'm aware of the repository scripts).

**Comment by rcalixte** [comment]
> My experience was different.

There have been other translation issues with your setup before right? Have those been resolved?

**Comment by schorschii** [comment]
I didn't notice any translation issues before.

**Pull request merged**
