### PR TITLE
[googleCalendar@javahelps.com] Migrate Google Calendar desklet to gcalendar

### LINKED ISSUE #509: Can't authenticate when first installing desklet - googleCalendar@javahelps.com
```
 * Desklet version: Default Google Calendar's desklet from Mint - last modified 04/02/2020
 * Cinnamon version: 4.2.4
 * Distribution: Mint 19.2 Cinnamon
 * Graphics hardware: GeForce MX150
 * Driver: xserver-xorg-video-nouveau ver 1.0.15-2

I just installed Google Calendar's desklet and got this when clicking the plus button to add the desklet:

> The "Sign in with Google" option is temporarily disabled for this app
> This app has not yet been verified by Google to use Google Login.

I'm following these steps and got the error in step 3:
https://cinnamon-spices.linuxmint.com/desklets/view/35

### PR DESCRIPTION
**Pull request by slgobinath**
There were some challenges in getting Google Calendar Desklet to get verified by Google for its Google Calendar API usage. Therefore I created new FOSS command-line tool named [gcalendar](https://github.com/slgobinath/gcalendar) and got it verified by Google.

Using `gcalendar` as the backend also reduces the complexity to setup this desklet and make it easy to track bugs related to gcalendar and desklet separately.

This MR also brings multiple accounts support.

@brownsr please check this MR

Fix #509

### CODE REVIEW

**Comment by slgobinath** [comment]
@brownsr sorry for bothering. Please check this MR.

Thanks

**Comment by brownsr** [comment]
I have some reservations about this PR to be honest.  Not about the code, but about the fact that it uses an associated PPA.  We use our repos for 3rd party applets/desklets so that we can be sure there is no malicious code in there, and keep our userbase secure in that respect. We have no such guarantee over other people's repos.  In this case the combination of desklet and associated PPA is causing me some head scratching.  I am asking within the team, so it may be a little time before I get back to you.

**Comment by slgobinath** [comment]
It makes sense. I am providing a PPA to make the setup process simple (users are complaining about the current installation process). What if I replace the installation via PPA by either installing from [pypi](https://pypi.org/project/gcalendar/) or from (source)[https://github.com/slgobinath/gcalendar]?

Commands would look like this respectively:

From PyPi
```
sudo apt install python3-pip python3-setuptools python3-dateutil python3-oauth2client python3-googleapi
pip3 install gcalendar
```

or

From Source:
```
sudo apt install python3-pip python3-setuptools python3-dateutil python3-oauth2client python3-googleapi git
git clone https://github.com/slgobinath/gcalendar.git
cd gcalendar
pip3 install -e .
```

My only concern is that users have to deal with any pip related issues and manually install the dependencies.

Another option would be getting gcalendar in the official repo but I think it takes a long time. One of my FOSS app (safeeyes) was submitted by a user to Debian repo and it took a looooong time to be available in Ubuntu & Linux Mint repo.

**Comment by brownsr** [comment]
I think all we need to do here is for you to add a comment in the readme where you mention the ppa, that the ppa is from a repository that is not monitored by the Mint team, and that the user installs it at their own discretion. I can merge it then.

If you add the alternative instructions above in the readme that would also be useful.  Some people will be wary of PPAs anyway, and they might prefer that.

Regards

Simon

**Comment by slgobinath** [comment]
Please note that I have added a disclaimer about the PPA and also included the alternative installation options to the read me file.

Thanks & Regards

**Comment by brownsr** [comment]
:-)

**Comment by slgobinath** [comment]
Hi Simon,

I tried to download the updated desklet but still it downloads the previous version. Tried on my LM 19.3 and the latest Manjaro Cinnamon on VM but both downloads the older version.
Am I missing anything in the MR?

Thanks & Regards,
Gobinath

**Comment by slgobinath** [comment]
https://cinnamon-spices.linuxmint.com/files/desklets/googleCalendar@javahelps.com.zip contains the old code.

**Comment by brownsr** [comment]
A number of people have reported an intermittent problem like this.  I'll see if we can get to the bottom of it.

**Pull request merged**
