### PR TITLE
Google Calendar desklet

### PR DESCRIPTION
**Pull request by slgobinath**
Hi,
This desklet shows the agenda retrieved using `gcalcli` on Cinnamon desktop as a sexy list. If there are any changes required, please do let me know.

Thanks & Regards,
Gobinath

### CODE REVIEW

**Comment by NikoKrause** [comment]
The lines dangerous and last-edited in metadata should be removed

**Comment by slgobinath** [comment]
Hi @NikoKrause,
Please find the changes made in the new commit https://github.com/linuxmint/cinnamon-spices-desklets/pull/179/commits/3799d03fef935963892a1a6d68ca2c50ea86a3a5.

Thanks

**Comment by NikoKrause** [comment]
Files as desklet.js, metadata.json and stylesheet.css don't need to be executable

**Comment by slgobinath** [comment]
@NikoKrause,
The file permissions are changed with the last commit.

Thanks

**Comment by NikoKrause** [comment]
As far as I tested, it seems ok.
But I don't use Google calendar.

@jaszhix Can you take a look?

**Comment by jaszhix** [comment]
It launches for me, and works. I'll merge it, but there's a few things that should be fixed at your convenience. Seen in .xsession-errors (or ```cinnnamon --replace```):

```
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js 5]: test for equality (==) mistyped as assignment (=)?
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js 16]: test for equality (==) mistyped as assignment (=)?
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/desklet.js 153]: reference to undefined property Settings.BindingDirection.ONE_WAY
```

In Cinnamon 3.2+, we can use ```settings.bind(<json-key>, <settingPropertyInClass>, <callback>)```.

**Comment by slgobinath** [comment]
@NikoKrause and @jaszhix,
Thanks for your support. I will fix them soon.

Thanks

**Pull request merged**
