### PR TITLE
Remove gcalcli dependency

### PR DESCRIPTION
**Pull request by slgobinath**
Hi @jaszhix 
This PR removes the `gcalcli` dependency and introduces `Python 3` and `google-api-python-client` dependencies. Depending on `gcalcli` breaks the desklet whenever there is a change in `gcalcli` command-line arguments and bugs in `gcalcli` also affect this desklet (See: #330) Furthermore, depending on `gcalcli` limits the functionality of the desklet.

In this PR, I have written my own Python script using `google-api-python-client` which can pull the calendar events and pass them to the desket. It allows me to add the following features:
- Show colored bullets differentiating the calendars
- Show the location of an event if it is available

However, I am afraid about the number of requests permitted by Google for my free Google Calendar Desklet API application. `gcalcli` faced this problem sometimes back and fixed it by requesting Google to increase the quota. I also request your help in testing this desklet in different Linux Mint versions which are currently being supported.

Could you please test this PR and let me know whether it can be merged?

Thanks & Regards

### CODE REVIEW

**Comment by slgobinath** [comment]
Hi @jaszhix,

Currently, there are two Codacy warnings for this PR:
1. 'imports' is not defined. (no-undef)
2. Identifier 'x_fill' is not in camel case. (camelcase)

However, I think they cannot be fixed because they are API calls. Could you please check whether they can be fixed or not?

Thanks

**Comment by jaszhix** [comment]
Hi @slgobinath, I'm only able to test on Cinnamon from git master at the moment, but these will probably apply to 3.8.

When I first added the desklet it looks like it had trouble parsing JSON, so nothing showed up.

```
Cjs-Message: 02:33:43.445: JS LOG: [LookingGlass/error] JSON.parse: unexpected character at line 1 column 1 of the JSON data
Cjs-Message: 02:33:43.445: JS LOG: [LookingGlass/trace] 
<----------------
addEvent@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/desklet.js:169:22
anonymous/retrieveEvents/<@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/desklet.js:310:21
SpawnReader.prototype.read/<@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/utility.js:66:13
---------------->
```

I restarted Cinnamon and the desklet showed up, with some errors. For these you just need to use `var` on the variable being accessed instead of const/let.


```

(cinnamon:21979): Cjs-WARNING **: 02:32:35.515: Some code accessed the property 'XDate' on the module 'utility'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(cinnamon:21979): Cjs-WARNING **: 02:32:35.515: Some code accessed the property 'SpawnReader' on the module 'utility'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(cinnamon:21979): Cjs-WARNING **: 02:32:35.515: Some code accessed the property 'CalendarUtility' on the module 'utility'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
```

```
Cjs-Message: 02:32:35.512: JS WARNING: [/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js 13]: test for equality (==) mistyped as assignment (=)?
Cjs-Message: 02:32:35.669: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function 71]: reference to undefined property "eventsList"
Cjs-Message: 02:32:35.678: JS WARNING: [/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/utility.js 50]: assignment to undeclared variable res
Cjs-Message: 02:32:38.550: JS WARNING: [/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js 13]: reference to undefined property "-1"
Cjs-Message: 02:32:38.552: JS LOG: [LookingGlass/error] JSON.parse: unexpected character at line 1 column 1 of the JSON data
Cjs-Message: 02:32:38.552: JS LOG: [LookingGlass/trace] 
<----------------
addEvent@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/desklet.js:169:22
anonymous/retrieveEvents/<@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/desklet.js:310:21
SpawnReader.prototype.read/<@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/utility.js:66:13
---------------->
```

I then authenticated successfully, but the applet didn't update. Restarted Cinnamon again, saw many of the same errors above, and it didn't load again.

Normally any time an xlet fails there's a stack trace, but I think it might be getting lost in one of the try-catch blocks. Cinnamon catches and handles any xlet failure, so I recommend using them to handle specific errors instead of a catching large blocks. Better for performance too.

**Comment by jaszhix** [comment]
Also, to answer your question about Codacy. It can actually be configured to validate based on how you want your code to be styled. Just [create an .eslintrc file](http://rapilabs.github.io/eslintrc-generator/) and place it in the root of your directory. ESlint is a great tool for spotting issues in code.

**Comment by slgobinath** [comment]
Hi @jaszhix,
Thank you very much for your feedback. Could you please run the following commands and share the outout you get?
```
cd ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py
python3 google_calendar.py
```

Thanks

**Comment by slgobinath** [comment]
BTW, you need to install `google-api-python-client` Python module. Please check the updated README

**Comment by jaszhix** [comment]
No, it didn't.

**Comment by slgobinath** [comment]
Hi,
Could you please install the following dependencies and run the python script again:
```
sudo apt install python3-pip
sudo apt install python3-setuptools
sudo pip3 install --upgrade python-dateutil google-api-python-client oauth2client
```

Then run the Python script:
```
cd ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py
python3 google_calendar.py
```

Thanks

**Comment by jaszhix** [comment]
Hi @slgobinath, that seems to work.

```
/usr/local/lib/python3.6/dist-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access calendar.dat: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?client_id=<redacted>
If your browser is on a different machine then exit and re-run this
application with the command-line parameter

  --noauth_local_webserver

Created new window in existing browser session.
Authentication successful.
```

The desklet doesn't start, though.

```
Cjs-Message: 07:32:24.282: JS WARNING: [/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js 13]: test for equality (==) mistyped as assignment (=)?

(cinnamon:9206): Cjs-WARNING **: 07:32:24.285: Some code accessed the property 'XDate' on the module 'utility'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(cinnamon:9206): Cjs-WARNING **: 07:32:24.285: Some code accessed the property 'SpawnReader' on the module 'utility'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(cinnamon:9206): Cjs-WARNING **: 07:32:24.285: Some code accessed the property 'CalendarUtility' on the module 'utility'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
```

It looks like the import errors are fixed in #346.

**Comment by slgobinath** [comment]
Hi,
I have merged the changes. Could you please try the desklet now?

Thanks

**Comment by jaszhix** [comment]
Tested this, when adding to the desktop it immediately opens the browser asking to give permission on google, that worked well. Afterwards (and once before on initial load), the log is spammed with

```
Cjs-Message: 17:50:53.978: JS LOG: [LookingGlass/trace] 
<----------------
addEvent@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/desklet.js:169:22
anonymous/retrieveEvents/<@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/desklet.js:328:21
SpawnReader.prototype.read/<@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/utility.js:66:13
---------------->
```

Desklet shows "Unable to retrieve events...". After restarting Cinnamon, it doesn't appear at all with no errors.

**Comment by slgobinath** [comment]
​Hi,
Do you have any events in your Google Calendar? When I execute the python script from the terminal, I got the following output. I will appreciate it if you can share yours (feel free to remove personal events).
```
[{"calendar_color": "#9fe1e7", "summary": "Test event", "start_date": "2018-12-04", "start_time": "08:30", "end_date": "2018-12-04", "end_time": "09:30", "location": ""}]
```

Thank you very much for taking your time to help me!

**Comment by slgobinath** [comment]
Closed in favor of #364

**Pull request closed without merging**
