### PR TITLE
Desklet : COVID-19 India Quick Stats - v1.1 updates

### PR DESCRIPTION
**Pull request by sujitagarwal**
1. Added 30-day graph feature. 
2. Better styling added.
3. Increased timeout from 1 minute to 5 minutes for fetching updates.

### CODE REVIEW

**Comment by sujitagarwal** [comment]
Adding screenshot here for reviewers to see the expected output - 
Screenshot from 2020-05-11 23-02-57

**Comment by sujitagarwal** [comment]
@brownsr a weird behaviour I'm seeing, when I try to install the Desklet from the Desklet Manager on my machine now, I still see the old version.
The changed files/readme/screenshots are showing on the cinnamon desklets website, but the installed desklet still shows old one.
Any hint's on what went wrong? Is it the cache?

**Comment by OnlineLearningTutorials** [comment]
@sujitagarwal I think your update not publish for public. your codacy/PR Quality Review negative make it positive. For any help tell me, showing graph in desklet is good idea, thanks.

**Comment by sujitagarwal** [comment]
Codacy reviews normally fail for all desklet commits. You can check previous commits as well. I don't think/believe that should be the root cause

**Comment by sujitagarwal** [comment]
Nevermind, I think the issue was my local cache. I tried installing the widget on a different computer and it worked fine.

**Pull request merged**
