### PR TITLE
soundBox@scollins: Fix sliders for the latest Cinnamon

### PR DESCRIPTION
**Pull request by kawashiro**
To be fixed: https://github.com/linuxmint/cinnamon-spices-desklets/issues/781

### CODE REVIEW

**Comment by rcalixte** [comment]
@kawashiro Have you tested this on older versions of Cinnamon? We can always create a 5.4 folder and copy new code there. It would then only apply to Cinnamon 5.4+ which I believe is the breaking point here.

**Comment by kawashiro** [comment]
@rcalixte Could you please suggest me a distro with such an old Cinnamon provided? Even the last Debian has 5.6.8 installed. Hope, it would not be a Nix OS or Gentoo :)

Just want to check if it really backward compatible, because regarding the docs, this API was introduced a long time ago

**Comment by rcalixte** [comment]
> @rcalixte Could you please suggest me a distro with such an old Cinnamon provided? Even the last Debian has 5.6.8 installed. Hope, it would not be a Nix OS or Gentoo :)

Linux Mint 20.3 is still supported and in heavy usage. That has Cinnamon 5.2. If it works there, that should be okay.



> Just want to check if it really backward compatible, because regarding the docs, this API was introduced a long time ago

We can always merge it now and fix it later if there are issues.

**Comment by kawashiro** [comment]
Yep, I really broke backward compatibility. It really does not work on 5.2. Give me some time to come up with a workaround of that

**Comment by rcalixte** [comment]
> Yep, I really broke backward compatibility. It really does not work on 5.2. Give me some time to come up with a workaround of that

That already exists. We can create a 5.4 directory and put the new contents there.

**Comment by kawashiro** [comment]
Make sense, will return with a fix, I hope, tomorrow

**Comment by rcalixte** [comment]
> Make sense, will return with a fix, I hope, tomorrow

Shout if you need a hand and we can collaborate!

**Comment by rcalixte** [comment]
@kawashiro This is phenomenal! I pushed a change to restore the 2.8 folder without symlinks (just in case) and then updated the translation files. This folder likely won't need to be touched going forward. I also renamed the 5.2 directory to 4.6 as that is the earliest version that it should support. (I should've been clearer here.) And the same for 5.6 to 5.4 as that is the boundary for the breaking changes.

Are you interested in taking over as the maintainer for this desklet? This means you would be notified for issues (but not alone).

**Review by rcalixte — APPROVED** [review]

**Comment by kawashiro** [comment]
@rcalixte thank you for your support

> Are you interested in taking over as the maintainer for this desklet?
Let's have a try

**Pull request merged**
