### PR TITLE
Fix #296 and support Cinnamon 3.8

### LINKED ISSUE #296: googleCalendar@javahelps.com : Long midnight event tiltle truncation
```
 * Desklet version 2018-04-09 04:01 UTC
 * Cinnamon version 3.6.7
 * Distribution - Mint 18.3
 * Graphics hardware Integrated Corporation Sky Lake Intagrated Graphics
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of desklet**
@slgobinath

**Issue**
Event that span on multiple days and start at "00:00" (midnight) : long event title is not truncated and the desklet becomes huge.

**Steps to reproduce**
1. Create this event :
- Long event title
- Start at : 00:00 (midnight), any day
- End at : any time, the day after the selected start day
2. Refresh the desklet content.

**Expected behaviour**
The title should be truncated like any other events

**Other information**

### PR DESCRIPTION
**Pull request by slgobinath**
Fix https://github.com/linuxmint/cinnamon-spices-desklets/issues/296 and added support for Cinnamon 3.8

@NikoKrause  please check this PR.

Thanks

### CODE REVIEW

**Comment by slgobinath** [comment]
I only have Cinnamon 3.6. If possible, could anyone test this with Cinnamon 3.8?

Thanks

**Comment by jaszhix** [comment]
Doesn't load on Cinnamon 3.8, but not because of this PR.

Cjs-Message: 05:49:46.665: JS LOG: [LookingGlass/info] Installing settings for googleCalendar@javahelps.com
Cjs-Message: 05:49:46.666: JS LOG: [LookingGlass/info] Settings successfully installed for googleCalendar@javahelps.com
Cjs-Message: 05:49:46.667: JS WARNING: [/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js 13]: reference to undefined property "-1"
Cjs-Message: 05:49:46.670: JS LOG: [LookingGlass/error] assignment to undeclared variable reader
Cjs-Message: 05:49:46.670: JS LOG: [LookingGlass/trace] 
<----------------
retrieveEvents@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/desklet.js:268:22
updateLoop@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/desklet.js:221:9
_init@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/desklet.js:96:9
GoogleCalendarDesklet@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/desklet.js:53:5
main@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/desklet.js:292:19
_createDesklets@/usr/share/cinnamon/js/ui/deskletManager.js:314:19
_loadDesklet@/usr/share/cinnamon/js/ui/deskletManager.js:282:23
finishExtensionLoad@/usr/share/cinnamon/js/ui/deskletManager.js:174:14
Extension.prototype._init/<@/usr/share/cinnamon/js/ui/extension.js:246:17
---------------->

I did test this on 3.8 when opening https://github.com/linuxmint/Cinnamon/pull/7354, but I was also testing [another PR](https://github.com/linuxmint/Cinnamon/pull/7349) at the time, which used the native GJS importer instead - and strict mode wasn't enabled on it. 

You can test your code with strict mode by adding `'use strict'`; at the top of desklet.js.

**Comment by slgobinath** [comment]
@jaszhix thanks for your test results.
I have fixed the problem. Is it necessary to remove `'use strict';` from the script? Shall I commit the fix along with strict mode enabled?

**Comment by jaszhix** [comment]
@slgobinath No problem. Should be fine with or without it, but its not needed since Cinnamon prepends every xlet with `'use strict';` before running them.

**Comment by slgobinath** [comment]
Thanks, @jaszhix for your quick reply.
Please check my new commit.

**Comment by jaszhix** [comment]
Noticed this after testing again:

```
Cjs-Message: 06:45:37.350: JS LOG: [LookingGlass/error] Expected type utf8 for Argument 'text' but got type 'undefined'
Cjs-Message: 06:45:37.350: JS LOG: [LookingGlass/trace] 
<----------------
CalendarUtility.prototype.label@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/utility.js:75:5
addEventToWidget@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/desklet.js:189:24
addEvent@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/desklet.js:169:9
anonymous/retrieveEvents/<@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/desklet.js:278:21
SpawnReader.prototype.read/<@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/utility.js:66:13
---------------->
```

Not strict mode related, but I've seen rare cases where passing non-string values to Clutter.Actor.set_text crashes Cinnamon.

**Comment by slgobinath** [comment]
@jaszhix please note that I have added an additional check to avoid assigning `undefined` to the label. However, I wonder why it happens. Could you please share the output of the following command to track the exact problem.

```
gcalcli agenda "4/25/2018" "4/30/2018" --nostarted --tsv
```

Note that above command will print your agenda. Please replace anything personal with something else.

Thanks

**Comment by jaszhix** [comment]
Sure, I think this is because I haven't set up gcalcli, but here's the output.

```
jason@SANDY4:~/code/etc$ gcalcli agenda "4/25/2018" "4/30/2018" --nostarted --tsv
/usr/lib/python3/dist-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /home/jason/.gcalcli_oauth: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/v2/auth?client_id=232867676714.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Furlshortener&access_type=offline&response_type=code

If your browser is on a different machine then exit and re-run this
application with the command-line parameter

  --noauth_local_webserver

Created new window in existing browser session.
```

I tested the change, and it looks like it got further, but error'd out again. 

```
Cjs-Message: 10:03:58.204: JS WARNING: [/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/utility.js 119]: reference to undefined property 2
Cjs-Message: 10:03:58.205: JS WARNING: [/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js 13]: reference to undefined property 0
Cjs-Message: 10:03:58.205: JS LOG: [LookingGlass/error] e[0] is undefined
Cjs-Message: 10:03:58.205: JS LOG: [LookingGlass/trace] 
<----------------
D@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js:13:4188
i@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js:13:465
u@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js:13:254
it.clone@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js:13:7589
f@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js:13:1076
@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js:13:6121
formatEventDuration@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/utility.js:127:27
addEventToWidget@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/desklet.js:192:24
addEvent@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/desklet.js:169:9
anonymous/retrieveEvents/<@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/desklet.js:278:21
SpawnReader.prototype.read/<@/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/utility.js:66:13
---------------->
```

Maybe you can add a check if users have galcli authenticated before running the main routine, or maybe display a message, "Please configure gcalcli to continue". Its not a critical thing, but its nice to handle errors, so users know what happened. 

I went ahead and authenticated galcli, and it seems to be working. Looks handy. :)

Afterwards, I only get warnings.

```
Cjs-Message: 10:08:08.674: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function 70]: reference to undefined property "eventsList"
Cjs-Message: 10:08:08.675: JS WARNING: [/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js 13]: reference to undefined property "-1"
Cjs-Message: 10:08:08.684: JS WARNING: [/home/jason/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/utility.js 50]: assignment to undeclared variable res
```

**Comment by slgobinath** [comment]
Hi @jaszhix,
I tried to reproduce this error in my LM 18.3 with gcalcli v3.3.2. After deleting the `~/.gcalcli_oauth` file, refreshing the desklet opens Google authentication page in Firefox without throwing any error.
However, I have included a fix that should solve the problem in your case. If this fix works, please let me know.

Thanks

**Comment by slgobinath** [comment]
@jaszhix Now I have squashed and merged all commits into one to avoid messing up the repo.
Please merge this PR now.

Thanks

**Pull request merged**
