### PR TITLE
googleCalendar@javahelps.com - Add link to Google Calendar into context menu

### PR DESCRIPTION
**Pull request by claudiux**
Hi @slgobinath,

I propose you this feature: add a link to Google Calendar into context menu.

I always wanted to right-click to edit events in the calendar. It's made, now!

Best regards.
Claudiux

### CODE REVIEW

**Comment by slgobinath** [comment]
Hi @claudiux,
I am also looking for this feature :-)

Please add `"Open Google Calendar"` to [po/googleCalendar.pot](https://github.com/linuxmint/cinnamon-spices-desklets/blob/master/googleCalendar%40javahelps.com/files/googleCalendar%40javahelps.com/po/googleCalendar.pot).

Thanks

**Comment by claudiux** [comment]
Hi @slgobinath,

Glad to realize your dreams ;)

googleCalendar.pot and fr.po are now up to date. The icons too.

desklet.js has been modified to remove some Codacy warnings.

I do not understand why some imports are considered as variables by JSLint. ???

This desklet works like a charm. I like it so!

**Comment by slgobinath** [comment]
> I do not understand why some imports are considered as variables by JSLint. ???

Me neither

@jaszhix please check this PR.

Thanks

**Comment by jaszhix** [comment]
https://github.com/linuxmint/cinnamon-spices-desklets/pull/342#issuecomment-430911647

**Pull request merged**
