### PR TITLE
calculator@scollins:Fix broken rpn operators/#769

### LINKED ISSUE #769: Desktop Calculator (calculator@scollins): division not working in RPN mode
```
 * Desklet version/Build date: Version 2.0 (2021-09-27 18:21:29)
 * Cinnamon version: 5.2.7
 * Distribution - Linux Mint 20.3
 * Graphics hardware *and* driver:  Intel Core Processor Integrated Graphics Controller, i965 driver
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of desklet**
@collinss 

**Issue**
When in RPN mode, clicking on the division function when two numbers are in the stack does nothing.  Clicking a second time erases the second number.

**Steps to reproduce**
Type  a number, press enter, type a second number, press divide. Nothing happens.

**Expected behaviour**
Result of first number divided by second number.

**Other information**
okay in normal mode.

### PR DESCRIPTION
**Pull request by jrversteegh**
Some variable declarations/"let" statements appeared to be missing. Refactored the code a bit and avoided missing "let" statements. That should fix #769

### CODE REVIEW

**Comment by rcalixte** [comment]
cc @schorschii

**Review by rcalixte — APPROVED** [review]

**Comment by schorschii** [comment]
@jrversteegh Thanks for this fix.
@rcalixte Please give the desklet maintainer a little more time next time for having a look at it.

**Comment by rcalixte** [comment]
> @rcalixte Please give the desklet maintainer a little more time next time for having a look at it.

Sorry for the confusion @schorschii. Per the [README](https://github.com/linuxmint/cinnamon-spices-desklets#pull-requests-from-other-people), this was a bug fix for an open Issue and one week had lapsed from when you were notified. Without any indication from you one way or another, this was merged.

**Comment by schorschii** [comment]
> for an open Issue and one week had lapsed

For an open issue which I wasn't notified about... Your mention was the first time I heard about it and then the time for having a look at it was simply too short.

**Pull request merged**
