### PR TITLE
[xkcd@rjanja] Fix for mint 21

### PR DESCRIPTION
**Pull request by Sayanel01**
The desklet is broken on mint 21 due to newer version of CJS:
 * newest Clutter version removed `Clutter.Texture` : Replaced `Clutter.Texture` by `Clutter.Image` (for display the comic) + `GdkPixbuf` for loading image from file.
 * newest Soup version removed `Cinnamon.write_soup_message_to_stream(...)` : fixed using `stream.write_bytes()`

Also removed useless and now broken tooltip part

Also fixed warning about `Mainloop.source_remove()` that showed up in Cinnamon log due to `this._timeoutId` not being unset.
 
Nb: I couldn't find which versions are used by CJS exactly. Looks like Soup 2.4 and Clutter above 7.

Nb 2 : Clutter project is now EOL (https://blogs.gnome.org/clutter/) so eventually it will have to be replaced.

Tested under Mint 20 and 21

### CODE REVIEW

**Comment by Sayanel01** [comment]
Note: fix for #821

**Comment by mtwebster** [comment]
Should this be versioned so it still works with Cinnamon < 5.4?

Also, soup 2 is going away - spices need to be ported to use soup3. Some details here:
https://libsoup.org/libsoup-3.0/migrating-from-libsoup-2.html

If you search thru the -applets, -desklets and -extensions repos you'll  see lots of commits for migrating - you can probably work from those (it's not a huge amount of work).

We do use api 7 of clutter. Clutter isn't going away, its been moved into the muffin package.


The gjs doc site is nice - https://gjs-docs.gnome.org/

You can import this config file there to set it up for most libraries used in Cinnamon (renamed to .txt so github would allow it):
[devdocs-cinnamon.json.txt](https://github.com/linuxmint/cinnamon-spices-desklets/files/10491921/devdocs-cinnamon.json.txt)

**Comment by Sayanel01** [comment]
> Should this be versioned so it still works with Cinnamon < 5.4?

I also tested with mint 19 Tara (Cinnamon 3.8.8), and it worked, so no. I didn't tested earlier version

> spices need to be ported to use soup3

I can't find a way to test with libsoup-3.0. I installed `libsoup-3.0-0` package and [tried](https://gjs.guide/guides/gjs/intro.html#in-a-gtk-application)

    imports.gi.versions.Soup = "3.0"
    const Soup = imports.gi.Soup

But that doesn't seems to be it: `Soup.get_major_version()` always return `2`. What should I do to test with soup 3?

**Comment by Sayanel01** [comment]
@mtwebster

**Comment by badmin-c** [comment]
I just downloaded the fixed desklet.js and replaced the old one. xkcd Desklet still does not work. Do I need something else changed?

**Comment by Sayanel01** [comment]
I think you need to restart cinnamon or reboot.

If that's not enough, I'll need more info. Which version of mint and cinnamon do you have?
Can you open looking glass (win+L), under "extensions", search xkcd, right click -> reload code
Then give me the end of the log ?

**Comment by badmin-c** [comment]
> I think you need to restart cinnamon or reboot.

Oh my... You're right. It works after reboot. Shame on me ^^

Thank you for your time!

**Pull request merged**
