### PR TITLE
timelet@linuxedo.com Mint 21.2 update

### LINKED ISSUE #865: timelet@linuxedo.com doesn't start on Mint 21.2 Cinnamon 5.8.4
```
 * 1680254874 = Friday, March 31, 2023 9:27:54 AM 
 * Cinnamon 5.8.4 
 * Mint 21.2
 * Graphics:
  

> Device-1: Intel TigerLake-LP GT2 [Iris Xe Graphics] vendor: Samsung Co driver: i915 v: kernel
>     ports: active: HDMI-A-2,eDP-1 empty: DP-1,HDMI-A-1 bus-ID: 00:02.0 chip-ID: 8086:9a49
>   Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting unloaded: fbdev,vesa
>     gpu: i915 display-ID: :0 screens: 1
>   OpenGL: renderer: Mesa Intel Xe Graphics (TGL GT2) v: 4.6 Mesa 23.2.0-devel (git-33f2ad9289)
>     direct render: Yes

 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors
   

> error t=2023-07-20T07:48:01Z [TypeError: GothamTheme is not a constructor]: Failed to evaluate 'main' function on desklet: timelet@linuxedo.com/24
> error t=2023-07-20T07:48:01Z 
> [timelet@linuxedo.com]: Desklet timelet@linuxedo.com: Could not create desklet object.
> [timelet@linuxedo.com]: Error importing desklet.js from timelet@linuxedo.com
> error t=2023-07-20T07:48:13Z [TypeError: GothamTheme is not a constructor]: Failed to evaluate 'main' function on desklet: timelet@linuxedo.com/24
> error t=2023-07-20T07:48:13Z 
> [timelet@linuxedo.com]: Desklet timelet@linuxedo.com: Could not create desklet object.
> [timelet@linuxedo.com]: Error importing desklet.js from timelet@linuxedo.com

 ```

**Notify author of desklet**
@slgobinath

**Issue**
Does not start either at startup or when launched manually

**Steps to reproduce**
Going in the desklets manager and adding Timelet dot not have effect, despite that it shows as ok.

**Expected behaviour**
Starting at startup, or starting when launched through the desklets manager

**Other information**
I already tried uninstalling and reinstalling

### PR DESCRIPTION
**Pull request by fredcw**
Make compatible with Mint 21.2
+Fix desklet not working in live image.

Fixes #865

@slgobinath

### CODE REVIEW

**Comment by slgobinath** [comment]
Thanks @fredcw & @claudiux 🙏 
I was affected by this issue too but couldn't dedicate enough time to find the solution (Not very familiar with JS and it wasn't obvious to me). Thanks for the fix!

Do you have any recommended way to run the code/check compile errors other than deploying locally and analyzing xerror logs?

**Comment by fredcw** [comment]
>deploying locally and analyzing xerror logs?

This is the only way to do it AFAIK.

**Comment by claudiux** [comment]
I recommend to use the Xsession applet to watch `~/.xsession-errors`, restart xlets and view their source code: https://cinnamon-spices.linuxmint.com/applets/view/362

**Comment by slgobinath** [comment]
Thanks @fredcw & @claudiux

**Pull request merged**
