### PR TITLE
calendar@deeppradhan: Added setting for first day of week (#295) + translations

### PR DESCRIPTION
**Pull request by OzzieIsaacs**
Made translation of texts working
Added missing texts for translation (day of week names, month names)
Added german translation
Added feature to set first day of the week

### CODE REVIEW

**Comment by jaszhix** [comment]
Please check contributing and put the name in the title.

**Comment by OzzieIsaacs** [comment]
@kanchudeep I added translations to your cinnamon-calendar-desklet and implemented change first day of week setting. Could you please approve the PR, and/or give me feedback for improvements.

Thanks

**Comment by kanchudeep** [comment]
Sorry @OzzieIsaacs ... Been busy... Will get back to you...

**Comment by brownsr** [comment]
ping @kanchudeep

**Comment by brownsr** [comment]
ping @kanchudeep

**Pull request closed without merging**
