### PR TITLE
Update desklet to use the new FileChooser correctly

### PR DESCRIPTION
**Pull request by JessW**
With the introduction of Cinnamon 3.2, this desklet stopped working.  It looks to me that the FileChooser interface changed, so I made the desklet multiversion to handle the two different interfaces pre- and post- Cinnamon 3.2.  It looks like a lot of changes because the 3.2 directory was created, but the actual code modifications were quite small if you compare the two desklet.js files.  

I am still a bit of a git newbie, so please let me know if anything looks incorrect with those merge commits.  I also don't quite understand why the commit on May 12 to change the author info is being included here, because I think that change is already included upstream.

### CODE REVIEW

**Comment by NikoKrause** [comment]
@JessW 
If you are new to git, maybe this will help you: https://github.com/NikoKrause/CinnVIIStarkMenu/issues/28

Please save your changes made here, before redoing stuff. So you don't loose your changes, if you delete something accidentally.

Info to this pull request. You have a po folder in the 3.2 folder.
There has to be only one `po` folder (with translations in it). And it has to be in the same directory as `metadata.json`.

**Comment by JessW** [comment]
@NikoKrause Thank you for pointing me toward the tutorial.  It is helpful, especially regarding branches. I am still a bit puzzled about the best way to keep my fork sync'd with the upstream repo.  I've tried following the steps at https://help.github.com/articles/syncing-a-fork/ , but when I do "git merge upstream/master", the text editor opens asking for an explanation of why the merge is necessary.  That isn't mentioned in the tutorial, but is that expected?

For these changes, would you recommend starting over, i.e. deleting my fork and recreating it, and creating the changes on their own branch, and then submitting a new pull request?

Thanks for pointing out that there should only be one po folder.  http://developer.linuxmint.com/reference/git/cinnamon-tutorials/xlet-versioning.html 
doesn't seem to mention this.  I can go ahead and submit a modification to the documentation there if that sounds reasonable.

I appreciate your patience!

**Comment by NikoKrause** [comment]
Read my tutorial. Never do changes on your master. Just keep it up to date with 
git pull upstream master

The tutorials there are not up to date

**Comment by JessW** [comment]
@NikoKrause Yes, I did read it, and read about git pull upstream master
before creating a branch, but I was wondering about keeping up to date with
upstream changes that occur later. Is that not an issue when working on a
branch other than master? Or just use git pull upstream master again?

Do you happen to have a recommendation for more up to date git help? Your
tutorial is great, but of course can't cover everything.

Thanks!

**Comment by NikoKrause** [comment]
Just use `git pull upstream master` again.

**Comment by JessW** [comment]
Thanks!

**Comment by JessW** [comment]
Will try this again with a cleaner pull request.

**Pull request closed without merging**
