### PR TITLE
Desklet manager not downloading latest feature may be version number …

### PR DESCRIPTION
**Pull request by OnlineLearningTutorials**
…a problem

### CODE REVIEW

**Comment by sujitagarwal** [comment]
I think this is the same issue that I was facing with my desklet's update

**Comment by OnlineLearningTutorials** [comment]
the downloaded code much like *All style placed in stylesheet.css* commit and same can be downloaded from [https://cinnamon-spices.linuxmint.com/desklets/view/53](cinnamon-spices website) , What is the issue of latest code? it depends on codecy review or updating after 2-3 days after pull commit. Please tell me.

**Comment by sujitagarwal** [comment]
I think you can try cleaning your cache. Or try from a different computer to see if your changes are reflecting

**Comment by OnlineLearningTutorials** [comment]
It updated today

**Pull request merged**
