### PR TITLE
New Desklet (deskNote@BrainAxe)

### PR DESCRIPTION
**Pull request by BrainAxe**
This is my first desklet. I hope this will merge with the main repository. Thanks

### CODE REVIEW

**Comment by NikoKrause** [comment]
A few notes:
* Please remove `dangerous` flag in metadata.
* The icon is 32x32 pixel. It will look blurry on the spices website. Ideal is 48x48 pixel.
* You use a bunch of imports, which you don't use in the applet:
```
-const Cinnamon = imports.gi.Cinnamon;
 const Gettext = imports.gettext;
 const GLib = imports.gi.GLib;
-const Lang = imports.lang;
-const Mainloop = imports.mainloop;
-const Util = imports.misc.util;
```
* To make the desklet translatable you might want to look into this: https://github.com/NikoKrause/CinnVIIStarkMenu/issues/19
* Bug: Using % to create a newline works for exactly one linebreak. Using a second %, the desklet just shows %. If you want to replace all % signs, use: `new_text.replace(/%/g, "\n")`.
* Using % for newlines introduces another bug: If I want to type a note `Buy alcohol: 15% max` I won't be able to show the % sign. If I were you, I would leave the default and write the note `use \n for newline` or use two `%%` signs for a newline: `new_text.replace(/%%/g, "\n")`

**Comment by NikoKrause** [comment]
P.S.: What does `Inspire Note` means? Do you mean `Inspiring Note`?

**Comment by BrainAxe** [comment]
Sorry @NikoKrause , I made so many mistakes. Thanks for your suggestions. I am solving the bugs now. By the way, Inspiring Note was the name at first I was thinking for the desklet and I forgot to replace the name.

**Comment by BrainAxe** [comment]
@NikoKrause  Sorry to bother you again, is it ok to not do the translation part? And also do I have to create another pull request for my desklet?

**Comment by NikoKrause** [comment]
The translation part is optional. 
I can do it later as soon as this is merged.

You don't need to create a new pull request. Just add another commit to your branch and it will appear in this PR.

**Comment by NikoKrause** [comment]
The images in the Readme in the spices website are broken.
You can link to
https://github.com/linuxmint/cinnamon-spices-desklets/blob/master/deskNote%40BrainAxe/icon.png

**Comment by BrainAxe** [comment]
I don't understand. It is good in GIthub.

**Comment by NikoKrause** [comment]
I mean here https://cinnamon-spices.linuxmint.com/desklets/view/36

**Comment by BrainAxe** [comment]
I found the error. The icon's link was not valid. I replace it and commit in my forked repository.

**Pull request merged**
