### PR TITLE
cpuload@kimse: align default width with diskspace desklet

### PR DESCRIPTION
**Pull request by schorschii**
Hi @ipimpat ,
I recently unified the default width of my desklets to 150px (#948) so that they better fit together on the desktop. Do you agree changing this on the cpuload desklet too? It would look really nice:
Bildschirmfoto vom 2023-11-06 14-58-01

### CODE REVIEW

**Review by AbdullahWins — COMMENTED** [review]
Well Done!

**Comment by ipimpat** [comment]
Hi @schorschii,

I appreciate the update on unifying the desklet widths to 150px, and the effort to improve desktop aesthetics sounds great. However, I'm no longer using Linux Mint / Cinnamon, so I feel it wouldn't be appropriate for me to comment on these changes. Best of luck with the continued developments!

**Comment by rcalixte** [comment]
@ipimpat We can set the author field to "none" (while still crediting you as the original author) so that you're not tagged for future changes if you'd like.

**Comment by schorschii** [comment]
Thanks for your reply. I can take care of the desklet as new maintainer if you agree.

**Comment by ipimpat** [comment]
> I can take care of the desklet as new maintainer if you agree.

Feel free to do that :-)

**Comment by rcalixte** [comment]
@schorschii Feel free to push a new commit here and we can squash the changes together.

**Comment by rcalixte** [comment]
We can leave the original author in as `original_author` too.

**Comment by schorschii** [comment]
Sorry, I wasn't aware of the `original_author`.

**Review by rcalixte — APPROVED** [review]

**Comment by rcalixte** [comment]
No need for apologies! All good!

**Comment by schorschii** [comment]
Thanks for your prompt replies and fast PR merges @rcalixte. I really like how you maintain this repo. 👍

**Comment by rcalixte** [comment]
> Thanks for your prompt replies and fast PR merges @rcalixte. I really like how you maintain this repo. 👍

Thanks for the kind words! I appreciate your contributions! I have a few installed everywhere I have Cinnamon. 😅

**Pull request merged**
