### PR TITLE
Proposals for cpuload@kimse

### PR DESCRIPTION
**Pull request by schorschii**
Hi @ipimpat 

I'm using the cpuload and diskspace desklet, which gave me the following ideas to improve the UX for people using both. Hope you like it.

- I propose to change the circle to a "speedometer-like" design. The speedometer design is more common for CPU usage visualization and users can differentiate it from the diskspace desklet on the first sight.
- I propose to adjust the default size to match the default diskspace desklet size.
- I added the new compact design known from the diskspace desklet.

Bildschirmfoto vom 2020-10-01 15-52-56
Bildschirmfoto vom 2020-10-01 15-56-33

### CODE REVIEW

**Comment by brownsr** [comment]
This hasn't moved forward for a time.  Still working on it ?

Regards

Simon

**Comment by schorschii** [comment]
The proposal is complete from my point of view. Waiting for @ipimpat 's opinion on it.
If you don't like the "speedometer-like" design, I would still recommend the other changes in order to to conform with the diskspace desklet, so both appear more homogeneous if the user uses both on the desktop.

**Comment by ipimpat** [comment]
I like the proposals very much, I just havn't got around around to test it tho.

Can the changes still be merged right in or is there conflicts that has to be resolved ?

**Comment by NikoKrause** [comment]
@schorschii This pull request has conflicts with the translation template and the German translation file.

**Pull request merged**
