### PR TITLE
Initial commit of Mintoo

### PR DESCRIPTION
**Pull request by sujitagarwal**
The Mintoo - The Mint Assistant is a friendly assistant for your Linux Mint that'll make your daily work flow easier. The current version supports the functionalities to lock screen, shutdown, reboot, logout from Linux Mint.

### CODE REVIEW

**Comment by sujitagarwal** [comment]
Hello, I wish to publish this Desklet and I can see it shows failures for code quality. But I ensured to follow all the code of existing Desklets to understand the coding pattern to meet the standards.

Most of the errors pointed out in the Code Review check look like false positives to me.
Any help would be appreciated...!

**Comment by brownsr** [comment]
Well I gave it a try, but nothing at all happened when pressing the buttons.  There are a lot of related warning messages in the .xsession-errors file, they look to be errors in the CSS:
(cinnamon:3786): St-WARNING **: 15:07:57.857: Ignoring length property that isn't a number at line 19, col 23

(cinnamon:3786): St-WARNING **: 15:07:57.858: Ignoring length property that isn't a number at line 53, col 23

(cinnamon:3786): St-WARNING **: 15:07:57.859: Ignoring length property that isn't a number at line 87, col 23

(cinnamon:3786): St-WARNING **: 15:07:57.860: Ignoring length property that isn't a number at line 120, col 23

(cinnamon:3786): St-WARNING **: 15:07:57.860: Ignoring length property that isn't a number at line 154, col 23

(cinnamon:3786): St-WARNING **: 15:08:17.063: Ignoring length property that isn't a number at line 53, col 23

(cinnamon:3786): St-WARNING **: 15:08:17.063: Ignoring length property that isn't a number at line 2, col 9

(cinnamon:3786): St-WARNING **: 15:08:17.064: Ignoring length property that isn't a number at line 19, col 23

(cinnamon:3786): St-WARNING **: 15:08:17.064: percentage lengths not currently supported

(cinnamon:3786): St-WARNING **: 15:08:17.064: Ignoring length property that isn't a number at line 53, col 23

(cinnamon:3786): St-WARNING **: 15:08:17.065: Ignoring length property that isn't a number at line 87, col 23

(cinnamon:3786): St-WARNING **: 15:08:17.065: percentage lengths not currently supported

(cinnamon:3786): St-WARNING **: 15:08:17.065: Ignoring length property that isn't a number at line 120, col 23

(cinnamon:3786): St-WARNING **: 15:08:17.065: Ignoring length property that isn't a number at line 154, col 23

(cinnamon:3786): St-WARNING **: 15:08:17.098: Ignoring length property that isn't a number at line 53, col 23

(cinnamon:3786): St-WARNING **: 15:08:17.098: Ignoring length property that isn't a number at line 87, col 23

(cinnamon:3786): St-WARNING **: 15:08:19.487: Ignoring length property that isn't a number at line 120, col 23

(cinnamon:3786): St-WARNING **: 15:08:21.683: Ignoring length property that isn't a number at line 53, col 23

(cinnamon:3786): St-WARNING **: 15:08:24.308: Ignoring length property that isn't a number at line 87, col 23

(cinnamon:3786): St-WARNING **: 15:08:24.732: Ignoring length property that isn't a number at line 154, col 23

(cinnamon:3786): St-WARNING **: 15:08:25.254: Ignoring length property that isn't a number at line 154, col 23

(cinnamon:3786): St-WARNING **: 15:08:25.884: Ignoring length property that isn't a number at line 120, col 23

**Comment by brownsr** [comment]
Ah I see, needs to be double click and meet a timing threshold at that.  A bit confusing, but it functions.  I'll merge it and leave it to you to address the CSS and think about whether the click functionality can be improved or configured to a user's needs.

Regards

Simon

**Comment by sujitagarwal** [comment]
@brownsr - thanks for pointing out the CSS issue, would fix that and send another PR for that.
Meanwhile, the buttons work on a double click to prevent any clicks by mistake. Also mentioned on the Readme File. This behaviour will be customizable with the settings feature that I am working on and adding as an enhancement

**Pull request merged**
