### PR TITLE
Nepali Patro Desklet: Initial commit

### PR DESCRIPTION
**Pull request by kanchudeep**
Nepali Patro Desklet - Highly configurable desklet for the Nepali Patro/Calendar (Bikram Sambat).

**Note**: Based off the work of calendar@deeppradhan

### CODE REVIEW

**Comment by jaszhix** [comment]
I'm confused about the differences between this applet and the one you just PR'd, would the functionality here be able to be handled by calendar@deeppradhan?

**Comment by kanchudeep** [comment]
This Desklet specifically for [Bikram Sambat Calendar](https://en.wikipedia.org/wiki/Vikram_Samvat) (used in Nepal) and not the common Gregorian calendar.

It shares some of the code with ```calendar@deeppradhan```.

**Comment by jaszhix** [comment]
Hi kanchudeep, can you remove `calendar@deeppradhan` from this PR? Otherwise, it can be merged.

**Comment by kanchudeep** [comment]
@jaszhix, I'm unable to remove `calendar@deeppradhan`. Should I try creating a new pull request?

**Comment by jaszhix** [comment]
@kanchudeep If that's easier for you, sure.

**Pull request closed without merging**
