### PR TITLE
Add fan1 speed to simple system monitor

### PR DESCRIPTION
**Pull request by kmaounis**

### CODE REVIEW

**Comment by clefebvre** [comment]
Hi @kmaounis, are you the author of this desklet?

**Comment by kmaounis** [comment]
Hey @clefebvre, no but I wanted to propose a improvement . You can close the pull request

**Comment by clefebvre** [comment]
That's ok, but in that case I need @ariel's approval (hoping he's on github and still active).

**Comment by arielandrade** [comment]
Hi @clefebvre I'm Ariel (@ariel user was my cinnamon-spices user) sorry for the delay.
Hi @kmaounis, it's a great feature, do you still want to add it? 
If you do, we'll just need to provide a default "N/A" value for valueFanSpeed.text when the fan-speed-file can't be found, I've just made the same change for the thermal file in [https://github.com/linuxmint/cinnamon-spices-desklets/pull/15/commits/9adb4b75eb8a56befd0e6b8561e921c963644394](url)
Thank you!

**Pull request closed without merging**
