### PR TITLE
Add Fish completions for scripts

### PR DESCRIPTION
**Pull request by EmilyGraceSeville7cf**
✅ Will be available from Fish thanks to [this](https://github.com/fish-shell/fish-shell/pull/10707) PR when accepted.

# Screenshot

image

Features

For test-spice and validate-spice the following features are supported:

- Tab-completion for options

# Prerequisites

- [Fish shell](https://fishshell.com/)

### CODE REVIEW

**Comment by rcalixte** [comment]
@EmilyGraceSeville7cf Both of these scripts already feature usage information when run without parameters. Again, please familiarize yourself with some of the existing tooling and please be patient for feedback. The Discussions are probably the best starting point for some of these ideas instead of Pull Requests.

**Comment by EmilyGraceSeville7cf** [comment]
> @EmilyGraceSeville7cf Both of these scripts already feature usage information when run without parameters.

Yes, indeed, I've checked it before writing these simple completions. :) I'm personally Fish shell user and use Tab-completion all the time, that's why I've written these completions.

**Comment by rcalixte** [comment]
> use Tab-completion all the time

The most common parameter(s) to these scripts are the UUIDs which are the subdirectories. For most modern shells, those subdirectories should already autocomplete. For the switches, there are not that many that it merits having upstream autocompletion files for shells. (You are more than fine to use this locally. No one but you can decide that.) This also ignores that the majority of distributions default to Bash still, limiting the overall usefulness of this for the community.

**Comment by EmilyGraceSeville7cf** [comment]
Completions are moved to Fish shell project.

**Pull request closed without merging**
